/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountsPayableDue from './AccountsPayableDue';
import CostCenter from './CostCenter';
import Currency from './Currency';
import Provider from './Provider';

/**
 * The AccountsPayableViewModel model module.
 * @module model/AccountsPayableViewModel
 * @version v1
 */
class AccountsPayableViewModel {
    /**
     * Constructs a new <code>AccountsPayableViewModel</code>.
     * @alias module:model/AccountsPayableViewModel
     */
    constructor() { 
        
        AccountsPayableViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountsPayableViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountsPayableViewModel} obj Optional instance to populate.
     * @return {module:model/AccountsPayableViewModel} The populated <code>AccountsPayableViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountsPayableViewModel();

            if (data.hasOwnProperty('due')) {
                obj['due'] = AccountsPayableDue.constructFromObject(data['due']);
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = Provider.constructFromObject(data['provider']);
            }
            if (data.hasOwnProperty('cost_center')) {
                obj['cost_center'] = CostCenter.constructFromObject(data['cost_center']);
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = Currency.constructFromObject(data['currency']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AccountsPayableDue} due
 */
AccountsPayableViewModel.prototype['due'] = undefined;

/**
 * @member {module:model/Provider} provider
 */
AccountsPayableViewModel.prototype['provider'] = undefined;

/**
 * @member {module:model/CostCenter} cost_center
 */
AccountsPayableViewModel.prototype['cost_center'] = undefined;

/**
 * @member {module:model/Currency} currency
 */
AccountsPayableViewModel.prototype['currency'] = undefined;






export default AccountsPayableViewModel;

