/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import TestBalanceCustomer from './TestBalanceCustomer.js';

/**
 * The CreateTestBalanceByThirdpartyCommand model module.
 * @module model/CreateTestBalanceByThirdpartyCommand
 * @version v1
 */
class CreateTestBalanceByThirdpartyCommand {
    /**
     * Constructs a new <code>CreateTestBalanceByThirdpartyCommand</code>.
     * @alias module:model/CreateTestBalanceByThirdpartyCommand
     */
    constructor() { 
        
        CreateTestBalanceByThirdpartyCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateTestBalanceByThirdpartyCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateTestBalanceByThirdpartyCommand} obj Optional instance to populate.
     * @return {module:model/CreateTestBalanceByThirdpartyCommand} The populated <code>CreateTestBalanceByThirdpartyCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateTestBalanceByThirdpartyCommand();

            if (data.hasOwnProperty('account_start')) {
                obj['account_start'] = ApiClient.convertToType(data['account_start'], 'String');
            }
            if (data.hasOwnProperty('account_end')) {
                obj['account_end'] = ApiClient.convertToType(data['account_end'], 'String');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('month_start')) {
                obj['month_start'] = ApiClient.convertToType(data['month_start'], 'Number');
            }
            if (data.hasOwnProperty('month_end')) {
                obj['month_end'] = ApiClient.convertToType(data['month_end'], 'Number');
            }
            if (data.hasOwnProperty('includes_tax_difference')) {
                obj['includes_tax_difference'] = ApiClient.convertToType(data['includes_tax_difference'], 'Boolean');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = TestBalanceCustomer.constructFromObject(data['customer']);
            }
        }
        return obj;
    }


}

/**
 * Represents the account's start value.
 * @member {String} account_start
 */
CreateTestBalanceByThirdpartyCommand.prototype['account_start'] = undefined;

/**
 * Represents the account's end value.
 * @member {String} account_end
 */
CreateTestBalanceByThirdpartyCommand.prototype['account_end'] = undefined;

/**
 * Represents the year of the balance.
 * @member {Number} year
 */
CreateTestBalanceByThirdpartyCommand.prototype['year'] = undefined;

/**
 * Represents the initial month of the balance.
 * @member {Number} month_start
 */
CreateTestBalanceByThirdpartyCommand.prototype['month_start'] = undefined;

/**
 * Represents the final month of the balance.
 * @member {Number} month_end
 */
CreateTestBalanceByThirdpartyCommand.prototype['month_end'] = undefined;

/**
 * Represents whether the balance includes tax difference or not.
 * @member {Boolean} includes_tax_difference
 */
CreateTestBalanceByThirdpartyCommand.prototype['includes_tax_difference'] = undefined;

/**
 * @member {module:model/TestBalanceCustomer} customer
 */
CreateTestBalanceByThirdpartyCommand.prototype['customer'] = undefined;






export default CreateTestBalanceByThirdpartyCommand;

