/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The GlobalTaxCommand model module.
 * @module model/GlobalTaxCommand
 * @version v1
 */
class GlobalTaxCommand {
    /**
     * Constructs a new <code>GlobalTaxCommand</code>.
     * @alias module:model/GlobalTaxCommand
     */
    constructor() { 
        
        GlobalTaxCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GlobalTaxCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GlobalTaxCommand} obj Optional instance to populate.
     * @return {module:model/GlobalTaxCommand} The populated <code>GlobalTaxCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GlobalTaxCommand();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('percentage')) {
                obj['percentage'] = ApiClient.convertToType(data['percentage'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Represents the id of the global tax, the value of this field must be an integer  number that represents the unique id of the global tax.
 * @member {Number} id
 */
GlobalTaxCommand.prototype['id'] = undefined;

/**
 * Represents the percentage parametrized to the global tax
 * @member {Number} percentage
 */
GlobalTaxCommand.prototype['percentage'] = undefined;

/**
 * @member {Number} value
 */
GlobalTaxCommand.prototype['value'] = undefined;






export default GlobalTaxCommand;

