/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountGroup from './AccountGroup';
import AdditionalFields from './AdditionalFields';
import KeysProductsViewModel from './KeysProductsViewModel';
import Metadata from './Metadata';
import PriceListViewModel from './PriceListViewModel';
import Tax from './Tax';
import UnitProductsViewModel from './UnitProductsViewModel';
import Warehouse from './Warehouse';

/**
 * The ProductModel model module.
 * @module model/ProductModel
 * @version v1
 */
class ProductModel {
    /**
     * Constructs a new <code>ProductModel</code>.
     * @alias module:model/ProductModel
     */
    constructor() { 
        
        ProductModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductModel} obj Optional instance to populate.
     * @return {module:model/ProductModel} The populated <code>ProductModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('account_group')) {
                obj['account_group'] = AccountGroup.constructFromObject(data['account_group']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('stock_control')) {
                obj['stock_control'] = ApiClient.convertToType(data['stock_control'], 'Boolean');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('tax_classification')) {
                obj['tax_classification'] = ApiClient.convertToType(data['tax_classification'], 'String');
            }
            if (data.hasOwnProperty('tax_included')) {
                obj['tax_included'] = ApiClient.convertToType(data['tax_included'], 'Boolean');
            }
            if (data.hasOwnProperty('tax_consumption_value')) {
                obj['tax_consumption_value'] = ApiClient.convertToType(data['tax_consumption_value'], 'Number');
            }
            if (data.hasOwnProperty('taxes')) {
                obj['taxes'] = ApiClient.convertToType(data['taxes'], [Tax]);
            }
            if (data.hasOwnProperty('prices')) {
                obj['prices'] = ApiClient.convertToType(data['prices'], [PriceListViewModel]);
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = UnitProductsViewModel.constructFromObject(data['unit']);
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = KeysProductsViewModel.constructFromObject(data['key']);
            }
            if (data.hasOwnProperty('unit_label')) {
                obj['unit_label'] = ApiClient.convertToType(data['unit_label'], 'String');
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('additional_fields')) {
                obj['additional_fields'] = AdditionalFields.constructFromObject(data['additional_fields']);
            }
            if (data.hasOwnProperty('available_quantity')) {
                obj['available_quantity'] = ApiClient.convertToType(data['available_quantity'], 'Number');
            }
            if (data.hasOwnProperty('warehouses')) {
                obj['warehouses'] = ApiClient.convertToType(data['warehouses'], [Warehouse]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ProductModel.prototype['id'] = undefined;

/**
 * @member {String} code
 */
ProductModel.prototype['code'] = undefined;

/**
 * @member {String} name
 */
ProductModel.prototype['name'] = undefined;

/**
 * @member {module:model/AccountGroup} account_group
 */
ProductModel.prototype['account_group'] = undefined;

/**
 * @member {String} type
 */
ProductModel.prototype['type'] = undefined;

/**
 * @member {Boolean} stock_control
 */
ProductModel.prototype['stock_control'] = undefined;

/**
 * @member {Boolean} active
 */
ProductModel.prototype['active'] = undefined;

/**
 * @member {String} tax_classification
 */
ProductModel.prototype['tax_classification'] = undefined;

/**
 * @member {Boolean} tax_included
 */
ProductModel.prototype['tax_included'] = undefined;

/**
 * @member {Number} tax_consumption_value
 */
ProductModel.prototype['tax_consumption_value'] = undefined;

/**
 * @member {Array.<module:model/Tax>} taxes
 */
ProductModel.prototype['taxes'] = undefined;

/**
 * @member {Array.<module:model/PriceListViewModel>} prices
 */
ProductModel.prototype['prices'] = undefined;

/**
 * @member {module:model/UnitProductsViewModel} unit
 */
ProductModel.prototype['unit'] = undefined;

/**
 * @member {module:model/KeysProductsViewModel} key
 */
ProductModel.prototype['key'] = undefined;

/**
 * @member {String} unit_label
 */
ProductModel.prototype['unit_label'] = undefined;

/**
 * @member {String} reference
 */
ProductModel.prototype['reference'] = undefined;

/**
 * @member {String} description
 */
ProductModel.prototype['description'] = undefined;

/**
 * @member {module:model/AdditionalFields} additional_fields
 */
ProductModel.prototype['additional_fields'] = undefined;

/**
 * @member {Number} available_quantity
 */
ProductModel.prototype['available_quantity'] = undefined;

/**
 * @member {Array.<module:model/Warehouse>} warehouses
 */
ProductModel.prototype['warehouses'] = undefined;

/**
 * @member {module:model/Metadata} metadata
 */
ProductModel.prototype['metadata'] = undefined;






export default ProductModel;

