/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import MailViewModel from './MailViewModel.js';
import VoucherStampModel from './VoucherStampModel.js';

/**
 * The SendElectronicVoucherViewModel model module.
 * @module model/SendElectronicVoucherViewModel
 * @version v1
 */
class SendElectronicVoucherViewModel {
    /**
     * Constructs a new <code>SendElectronicVoucherViewModel</code>.
     * @alias module:model/SendElectronicVoucherViewModel
     */
    constructor() { 
        
        SendElectronicVoucherViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendElectronicVoucherViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendElectronicVoucherViewModel} obj Optional instance to populate.
     * @return {module:model/SendElectronicVoucherViewModel} The populated <code>SendElectronicVoucherViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendElectronicVoucherViewModel();

            if (data.hasOwnProperty('stamp')) {
                obj['stamp'] = VoucherStampModel.constructFromObject(data['stamp']);
            }
            if (data.hasOwnProperty('mail')) {
                obj['mail'] = MailViewModel.constructFromObject(data['mail']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/VoucherStampModel} stamp
 */
SendElectronicVoucherViewModel.prototype['stamp'] = undefined;

/**
 * @member {module:model/MailViewModel} mail
 */
SendElectronicVoucherViewModel.prototype['mail'] = undefined;






export default SendElectronicVoucherViewModel;

