/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The TestBalanceResultModel model module.
 * @module model/TestBalanceResultModel
 * @version v1
 */
class TestBalanceResultModel {
    /**
     * Constructs a new <code>TestBalanceResultModel</code>.
     * @alias module:model/TestBalanceResultModel
     */
    constructor() { 
        
        TestBalanceResultModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TestBalanceResultModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestBalanceResultModel} obj Optional instance to populate.
     * @return {module:model/TestBalanceResultModel} The populated <code>TestBalanceResultModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestBalanceResultModel();

            if (data.hasOwnProperty('file_id')) {
                obj['file_id'] = ApiClient.convertToType(data['file_id'], 'String');
            }
            if (data.hasOwnProperty('file_url')) {
                obj['file_url'] = ApiClient.convertToType(data['file_url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Represents the file's identifier.
 * @member {String} file_id
 */
TestBalanceResultModel.prototype['file_id'] = undefined;

/**
 * Represents the file's url.
 * @member {String} file_url
 */
TestBalanceResultModel.prototype['file_url'] = undefined;






export default TestBalanceResultModel;

