/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The VoucherStampModel model module.
 * @module model/VoucherStampModel
 * @version v1
 */
class VoucherStampModel {
    /**
     * Constructs a new <code>VoucherStampModel</code>.
     * @alias module:model/VoucherStampModel
     */
    constructor() { 
        
        VoucherStampModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VoucherStampModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VoucherStampModel} obj Optional instance to populate.
     * @return {module:model/VoucherStampModel} The populated <code>VoucherStampModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VoucherStampModel();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('observations')) {
                obj['observations'] = ApiClient.convertToType(data['observations'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Represents Unique electronic voucher code.
 * @member {String} uuid
 */
VoucherStampModel.prototype['uuid'] = undefined;

/**
 * It represents the status of the electronic document, it can be:  Draft: The document was saved correctly but this document.  was not sent to the tax collector entity.  Accepted: The document was sent and accepted correctly.  Rejected: The document was sent with errors therefore it was rejected.
 * @member {String} status
 */
VoucherStampModel.prototype['status'] = undefined;

/**
 * Represents observations associated with an electronic document.
 * @member {String} observations
 */
VoucherStampModel.prototype['observations'] = undefined;

/**
 * @member {String} errors
 */
VoucherStampModel.prototype['errors'] = undefined;






export default VoucherStampModel;

