/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DocumentBalanceViewModel from '../model/DocumentBalanceViewModel';

/**
* DocumentBalance service.
* @module api/DocumentBalanceApi
* @version v1
*/
export default class DocumentBalanceApi {

    /**
    * Constructs a new DocumentBalanceApi. 
    * @alias module:api/DocumentBalanceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Returns client document balance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/DocumentBalanceViewModel>} and HTTP response
     */
    getDocumentBalancesWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [DocumentBalanceViewModel];
      return this.apiClient.callApi(
        '/v1/available-documents', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Returns client document balance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/DocumentBalanceViewModel>}
     */
    getDocumentBalances() {
      return this.getDocumentBalancesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
