/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.AccountsPayableViewModelGetAllModel();
});

describe('AccountsPayableViewModelGetAllModel', function() {
  it('should create an instance of AccountsPayableViewModelGetAllModel', function() {
    // uncomment below and update the code to test AccountsPayableViewModelGetAllModel
    //var instance = new SiigoApi.AccountsPayableViewModelGetAllModel();
    //expect(instance).to.be.a(SiigoApi.AccountsPayableViewModelGetAllModel);
  });

  it('should have the property pagination (base name: "pagination")', function() {
    // uncomment below and update the code to test the property pagination
    //var instance = new SiigoApi.AccountsPayableViewModelGetAllModel();
    //expect(instance).to.be();
  });

  it('should have the property results (base name: "results")', function() {
    // uncomment below and update the code to test the property results
    //var instance = new SiigoApi.AccountsPayableViewModelGetAllModel();
    //expect(instance).to.be();
  });

  it('should have the property links (base name: "_links")', function() {
    // uncomment below and update the code to test the property links
    //var instance = new SiigoApi.AccountsPayableViewModelGetAllModel();
    //expect(instance).to.be();
  });

});
