/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.Account();
});

describe('Account', function() {
  it('should create an instance of Account', function() {
    // uncomment below and update the code to test Account
    //var instance = new SiigoApi.Account();
    //expect(instance).to.be.a(SiigoApi.Account);
  });

  it('should have the property code (base name: "code")', function() {
    // uncomment below and update the code to test the property code
    //var instance = new SiigoApi.Account();
    //expect(instance).to.be();
  });

  it('should have the property movement (base name: "movement")', function() {
    // uncomment below and update the code to test the property movement
    //var instance = new SiigoApi.Account();
    //expect(instance).to.be();
  });

});
