/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.AccountsPayableViewModel();
});

describe('AccountsPayableViewModel', function() {
  it('should create an instance of AccountsPayableViewModel', function() {
    // uncomment below and update the code to test AccountsPayableViewModel
    //var instance = new SiigoApi.AccountsPayableViewModel();
    //expect(instance).to.be.a(SiigoApi.AccountsPayableViewModel);
  });

  it('should have the property due (base name: "due")', function() {
    // uncomment below and update the code to test the property due
    //var instance = new SiigoApi.AccountsPayableViewModel();
    //expect(instance).to.be();
  });

  it('should have the property provider (base name: "provider")', function() {
    // uncomment below and update the code to test the property provider
    //var instance = new SiigoApi.AccountsPayableViewModel();
    //expect(instance).to.be();
  });

  it('should have the property costCenter (base name: "cost_center")', function() {
    // uncomment below and update the code to test the property costCenter
    //var instance = new SiigoApi.AccountsPayableViewModel();
    //expect(instance).to.be();
  });

  it('should have the property currency (base name: "currency")', function() {
    // uncomment below and update the code to test the property currency
    //var instance = new SiigoApi.AccountsPayableViewModel();
    //expect(instance).to.be();
  });

});
