/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.AdditionalFields();
});

describe('AdditionalFields', function() {
  it('should create an instance of AdditionalFields', function() {
    // uncomment below and update the code to test AdditionalFields
    //var instance = new SiigoApi.AdditionalFields();
    //expect(instance).to.be.a(SiigoApi.AdditionalFields);
  });

  it('should have the property barcode (base name: "barcode")', function() {
    // uncomment below and update the code to test the property barcode
    //var instance = new SiigoApi.AdditionalFields();
    //expect(instance).to.be();
  });

  it('should have the property brand (base name: "brand")', function() {
    // uncomment below and update the code to test the property brand
    //var instance = new SiigoApi.AdditionalFields();
    //expect(instance).to.be();
  });

  it('should have the property tariff (base name: "tariff")', function() {
    // uncomment below and update the code to test the property tariff
    //var instance = new SiigoApi.AdditionalFields();
    //expect(instance).to.be();
  });

  it('should have the property model (base name: "model")', function() {
    // uncomment below and update the code to test the property model
    //var instance = new SiigoApi.AdditionalFields();
    //expect(instance).to.be();
  });

});
