/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.AdditionalFieldsCommand();
});

describe('AdditionalFieldsCommand', function() {
  it('should create an instance of AdditionalFieldsCommand', function() {
    // uncomment below and update the code to test AdditionalFieldsCommand
    //var instance = new SiigoApi.AdditionalFieldsCommand();
    //expect(instance).to.be.a(SiigoApi.AdditionalFieldsCommand);
  });

  it('should have the property purchaseOrder (base name: "purchase_order")', function() {
    // uncomment below and update the code to test the property purchaseOrder
    //var instance = new SiigoApi.AdditionalFieldsCommand();
    //expect(instance).to.be();
  });

  it('should have the property deliveryOrder (base name: "delivery_order")', function() {
    // uncomment below and update the code to test the property deliveryOrder
    //var instance = new SiigoApi.AdditionalFieldsCommand();
    //expect(instance).to.be();
  });

});
