/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.AddressModel();
});

describe('AddressModel', function() {
  it('should create an instance of AddressModel', function() {
    // uncomment below and update the code to test AddressModel
    //var instance = new SiigoApi.AddressModel();
    //expect(instance).to.be.a(SiigoApi.AddressModel);
  });

  it('should have the property address (base name: "address")', function() {
    // uncomment below and update the code to test the property address
    //var instance = new SiigoApi.AddressModel();
    //expect(instance).to.be();
  });

  it('should have the property city (base name: "city")', function() {
    // uncomment below and update the code to test the property city
    //var instance = new SiigoApi.AddressModel();
    //expect(instance).to.be();
  });

  it('should have the property postalCode (base name: "postal_code")', function() {
    // uncomment below and update the code to test the property postalCode
    //var instance = new SiigoApi.AddressModel();
    //expect(instance).to.be();
  });

});
