/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.AddressCommand();
});

describe('AddressCommand', function() {
  it('should create an instance of AddressCommand', function() {
    // uncomment below and update the code to test AddressCommand
    //var instance = new SiigoApi.AddressCommand();
    //expect(instance).to.be.a(SiigoApi.AddressCommand);
  });

  it('should have the property address (base name: "address")', function() {
    // uncomment below and update the code to test the property address
    //var instance = new SiigoApi.AddressCommand();
    //expect(instance).to.be();
  });

  it('should have the property city (base name: "city")', function() {
    // uncomment below and update the code to test the property city
    //var instance = new SiigoApi.AddressCommand();
    //expect(instance).to.be();
  });

  it('should have the property postalCode (base name: "postal_code")', function() {
    // uncomment below and update the code to test the property postalCode
    //var instance = new SiigoApi.AddressCommand();
    //expect(instance).to.be();
  });

  it('should have the property street (base name: "street")', function() {
    // uncomment below and update the code to test the property street
    //var instance = new SiigoApi.AddressCommand();
    //expect(instance).to.be();
  });

  it('should have the property interiorNumber (base name: "interior_number")', function() {
    // uncomment below and update the code to test the property interiorNumber
    //var instance = new SiigoApi.AddressCommand();
    //expect(instance).to.be();
  });

  it('should have the property exteriorNumber (base name: "exterior_number")', function() {
    // uncomment below and update the code to test the property exteriorNumber
    //var instance = new SiigoApi.AddressCommand();
    //expect(instance).to.be();
  });

  it('should have the property colony (base name: "colony")', function() {
    // uncomment below and update the code to test the property colony
    //var instance = new SiigoApi.AddressCommand();
    //expect(instance).to.be();
  });

  it('should have the property locality (base name: "locality")', function() {
    // uncomment below and update the code to test the property locality
    //var instance = new SiigoApi.AddressCommand();
    //expect(instance).to.be();
  });

});
