/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.CityModel();
});

describe('CityModel', function() {
  it('should create an instance of CityModel', function() {
    // uncomment below and update the code to test CityModel
    //var instance = new SiigoApi.CityModel();
    //expect(instance).to.be.a(SiigoApi.CityModel);
  });

  it('should have the property countryCode (base name: "country_code")', function() {
    // uncomment below and update the code to test the property countryCode
    //var instance = new SiigoApi.CityModel();
    //expect(instance).to.be();
  });

  it('should have the property countryName (base name: "country_name")', function() {
    // uncomment below and update the code to test the property countryName
    //var instance = new SiigoApi.CityModel();
    //expect(instance).to.be();
  });

  it('should have the property stateCode (base name: "state_code")', function() {
    // uncomment below and update the code to test the property stateCode
    //var instance = new SiigoApi.CityModel();
    //expect(instance).to.be();
  });

  it('should have the property stateName (base name: "state_name")', function() {
    // uncomment below and update the code to test the property stateName
    //var instance = new SiigoApi.CityModel();
    //expect(instance).to.be();
  });

  it('should have the property cityCode (base name: "city_code")', function() {
    // uncomment below and update the code to test the property cityCode
    //var instance = new SiigoApi.CityModel();
    //expect(instance).to.be();
  });

  it('should have the property cityName (base name: "city_name")', function() {
    // uncomment below and update the code to test the property cityName
    //var instance = new SiigoApi.CityModel();
    //expect(instance).to.be();
  });

});
