/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.ContactCommand();
});

describe('ContactCommand', function() {
  it('should create an instance of ContactCommand', function() {
    // uncomment below and update the code to test ContactCommand
    //var instance = new SiigoApi.ContactCommand();
    //expect(instance).to.be.a(SiigoApi.ContactCommand);
  });

  it('should have the property firstName (base name: "first_name")', function() {
    // uncomment below and update the code to test the property firstName
    //var instance = new SiigoApi.ContactCommand();
    //expect(instance).to.be();
  });

  it('should have the property lastName (base name: "last_name")', function() {
    // uncomment below and update the code to test the property lastName
    //var instance = new SiigoApi.ContactCommand();
    //expect(instance).to.be();
  });

  it('should have the property email (base name: "email")', function() {
    // uncomment below and update the code to test the property email
    //var instance = new SiigoApi.ContactCommand();
    //expect(instance).to.be();
  });

  it('should have the property phone (base name: "phone")', function() {
    // uncomment below and update the code to test the property phone
    //var instance = new SiigoApi.ContactCommand();
    //expect(instance).to.be();
  });

});
