/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.CreateTestBalanceCommand();
});

describe('CreateTestBalanceCommand', function() {
  it('should create an instance of CreateTestBalanceCommand', function() {
    // uncomment below and update the code to test CreateTestBalanceCommand
    //var instance = new SiigoApi.CreateTestBalanceCommand();
    //expect(instance).to.be.a(SiigoApi.CreateTestBalanceCommand);
  });

  it('should have the property accountStart (base name: "account_start")', function() {
    // uncomment below and update the code to test the property accountStart
    //var instance = new SiigoApi.CreateTestBalanceCommand();
    //expect(instance).to.be();
  });

  it('should have the property accountEnd (base name: "account_end")', function() {
    // uncomment below and update the code to test the property accountEnd
    //var instance = new SiigoApi.CreateTestBalanceCommand();
    //expect(instance).to.be();
  });

  it('should have the property year (base name: "year")', function() {
    // uncomment below and update the code to test the property year
    //var instance = new SiigoApi.CreateTestBalanceCommand();
    //expect(instance).to.be();
  });

  it('should have the property monthStart (base name: "month_start")', function() {
    // uncomment below and update the code to test the property monthStart
    //var instance = new SiigoApi.CreateTestBalanceCommand();
    //expect(instance).to.be();
  });

  it('should have the property monthEnd (base name: "month_end")', function() {
    // uncomment below and update the code to test the property monthEnd
    //var instance = new SiigoApi.CreateTestBalanceCommand();
    //expect(instance).to.be();
  });

  it('should have the property includesTaxDifference (base name: "includes_tax_difference")', function() {
    // uncomment below and update the code to test the property includesTaxDifference
    //var instance = new SiigoApi.CreateTestBalanceCommand();
    //expect(instance).to.be();
  });

});
