/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.CreateJournalEntryCommand();
});

describe('CreateJournalEntryCommand', function() {
  it('should create an instance of CreateJournalEntryCommand', function() {
    // uncomment below and update the code to test CreateJournalEntryCommand
    //var instance = new SiigoApi.CreateJournalEntryCommand();
    //expect(instance).to.be.a(SiigoApi.CreateJournalEntryCommand);
  });

  it('should have the property document (base name: "document")', function() {
    // uncomment below and update the code to test the property document
    //var instance = new SiigoApi.CreateJournalEntryCommand();
    //expect(instance).to.be();
  });

  it('should have the property number (base name: "number")', function() {
    // uncomment below and update the code to test the property number
    //var instance = new SiigoApi.CreateJournalEntryCommand();
    //expect(instance).to.be();
  });

  it('should have the property date (base name: "date")', function() {
    // uncomment below and update the code to test the property date
    //var instance = new SiigoApi.CreateJournalEntryCommand();
    //expect(instance).to.be();
  });

  it('should have the property currency (base name: "currency")', function() {
    // uncomment below and update the code to test the property currency
    //var instance = new SiigoApi.CreateJournalEntryCommand();
    //expect(instance).to.be();
  });

  it('should have the property items (base name: "items")', function() {
    // uncomment below and update the code to test the property items
    //var instance = new SiigoApi.CreateJournalEntryCommand();
    //expect(instance).to.be();
  });

  it('should have the property observations (base name: "observations")', function() {
    // uncomment below and update the code to test the property observations
    //var instance = new SiigoApi.CreateJournalEntryCommand();
    //expect(instance).to.be();
  });

});
