/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.CreditNotePdfViewModel();
});

describe('CreditNotePdfViewModel', function() {
  it('should create an instance of CreditNotePdfViewModel', function() {
    // uncomment below and update the code to test CreditNotePdfViewModel
    //var instance = new SiigoApi.CreditNotePdfViewModel();
    //expect(instance).to.be.a(SiigoApi.CreditNotePdfViewModel);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SiigoApi.CreditNotePdfViewModel();
    //expect(instance).to.be();
  });

  it('should have the property cude (base name: "cude")', function() {
    // uncomment below and update the code to test the property cude
    //var instance = new SiigoApi.CreditNotePdfViewModel();
    //expect(instance).to.be();
  });

  it('should have the property base64 (base name: "base64")', function() {
    // uncomment below and update the code to test the property base64
    //var instance = new SiigoApi.CreditNotePdfViewModel();
    //expect(instance).to.be();
  });

});
