/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.CurrencyCommand();
});

describe('CurrencyCommand', function() {
  it('should create an instance of CurrencyCommand', function() {
    // uncomment below and update the code to test CurrencyCommand
    //var instance = new SiigoApi.CurrencyCommand();
    //expect(instance).to.be.a(SiigoApi.CurrencyCommand);
  });

  it('should have the property code (base name: "code")', function() {
    // uncomment below and update the code to test the property code
    //var instance = new SiigoApi.CurrencyCommand();
    //expect(instance).to.be();
  });

  it('should have the property exchangeRate (base name: "exchange_rate")', function() {
    // uncomment below and update the code to test the property exchangeRate
    //var instance = new SiigoApi.CurrencyCommand();
    //expect(instance).to.be();
  });

});
