/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.Currency();
});

describe('Currency', function() {
  it('should create an instance of Currency', function() {
    // uncomment below and update the code to test Currency
    //var instance = new SiigoApi.Currency();
    //expect(instance).to.be.a(SiigoApi.Currency);
  });

  it('should have the property moneyCode (base name: "money_code")', function() {
    // uncomment below and update the code to test the property moneyCode
    //var instance = new SiigoApi.Currency();
    //expect(instance).to.be();
  });

  it('should have the property balance (base name: "balance")', function() {
    // uncomment below and update the code to test the property balance
    //var instance = new SiigoApi.Currency();
    //expect(instance).to.be();
  });

});
