/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.CustomFieldsCommand();
});

describe('CustomFieldsCommand', function() {
  it('should create an instance of CustomFieldsCommand', function() {
    // uncomment below and update the code to test CustomFieldsCommand
    //var instance = new SiigoApi.CustomFieldsCommand();
    //expect(instance).to.be.a(SiigoApi.CustomFieldsCommand);
  });

  it('should have the property key (base name: "key")', function() {
    // uncomment below and update the code to test the property key
    //var instance = new SiigoApi.CustomFieldsCommand();
    //expect(instance).to.be();
  });

  it('should have the property value (base name: "value")', function() {
    // uncomment below and update the code to test the property value
    //var instance = new SiigoApi.CustomFieldsCommand();
    //expect(instance).to.be();
  });

});
