/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
});

describe('DianReason', function() {
  it('should create an instance of DianReason', function() {
    // uncomment below and update the code to test DianReason
    //var instance = new SiigoApi.DianReason();
    //expect(instance).to.be.a(SiigoApi.DianReason);
  });

});
