/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.DiscountModel();
});

describe('DiscountModel', function() {
  it('should create an instance of DiscountModel', function() {
    // uncomment below and update the code to test DiscountModel
    //var instance = new SiigoApi.DiscountModel();
    //expect(instance).to.be.a(SiigoApi.DiscountModel);
  });

  it('should have the property percentage (base name: "percentage")', function() {
    // uncomment below and update the code to test the property percentage
    //var instance = new SiigoApi.DiscountModel();
    //expect(instance).to.be();
  });

  it('should have the property value (base name: "value")', function() {
    // uncomment below and update the code to test the property value
    //var instance = new SiigoApi.DiscountModel();
    //expect(instance).to.be();
  });

});
