/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.DocumentTypeViewModel();
});

describe('DocumentTypeViewModel', function() {
  it('should create an instance of DocumentTypeViewModel', function() {
    // uncomment below and update the code to test DocumentTypeViewModel
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be.a(SiigoApi.DocumentTypeViewModel);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property code (base name: "code")', function() {
    // uncomment below and update the code to test the property code
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property name (base name: "name")', function() {
    // uncomment below and update the code to test the property name
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property description (base name: "description")', function() {
    // uncomment below and update the code to test the property description
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property type (base name: "type")', function() {
    // uncomment below and update the code to test the property type
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property active (base name: "active")', function() {
    // uncomment below and update the code to test the property active
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property sellerByItem (base name: "seller_by_item")', function() {
    // uncomment below and update the code to test the property sellerByItem
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property costCenter (base name: "cost_center")', function() {
    // uncomment below and update the code to test the property costCenter
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property costCenterMandatory (base name: "cost_center_mandatory")', function() {
    // uncomment below and update the code to test the property costCenterMandatory
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property costCenterDefault (base name: "cost_center_default")', function() {
    // uncomment below and update the code to test the property costCenterDefault
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property automaticNumber (base name: "automatic_number")', function() {
    // uncomment below and update the code to test the property automaticNumber
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property consecutive (base name: "consecutive")', function() {
    // uncomment below and update the code to test the property consecutive
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property discountType (base name: "discount_type")', function() {
    // uncomment below and update the code to test the property discountType
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property decimals (base name: "decimals")', function() {
    // uncomment below and update the code to test the property decimals
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property advancePayment (base name: "advance_payment")', function() {
    // uncomment below and update the code to test the property advancePayment
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property reteiva (base name: "reteiva")', function() {
    // uncomment below and update the code to test the property reteiva
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property reteica (base name: "reteica")', function() {
    // uncomment below and update the code to test the property reteica
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property selfWithholding (base name: "self_withholding")', function() {
    // uncomment below and update the code to test the property selfWithholding
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property selfWithholdingLimit (base name: "self_withholding_limit")', function() {
    // uncomment below and update the code to test the property selfWithholdingLimit
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property electronicType (base name: "electronic_type")', function() {
    // uncomment below and update the code to test the property electronicType
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property officialBook (base name: "official_book")', function() {
    // uncomment below and update the code to test the property officialBook
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property documentSupport (base name: "document_support")', function() {
    // uncomment below and update the code to test the property documentSupport
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property prefix (base name: "prefix")', function() {
    // uncomment below and update the code to test the property prefix
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property globalDiscounts (base name: "global_discounts")', function() {
    // uncomment below and update the code to test the property globalDiscounts
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property globalCharges (base name: "global_charges")', function() {
    // uncomment below and update the code to test the property globalCharges
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property cargoTransportation (base name: "cargo_transportation")', function() {
    // uncomment below and update the code to test the property cargoTransportation
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property iSR (base name: "i_s_r")', function() {
    // uncomment below and update the code to test the property iSR
    //var instance = new SiigoApi.DocumentTypeViewModel();
    //expect(instance).to.be();
  });

});
