/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.DocumentVoucher();
});

describe('DocumentVoucher', function() {
  it('should create an instance of DocumentVoucher', function() {
    // uncomment below and update the code to test DocumentVoucher
    //var instance = new SiigoApi.DocumentVoucher();
    //expect(instance).to.be.a(SiigoApi.DocumentVoucher);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SiigoApi.DocumentVoucher();
    //expect(instance).to.be();
  });

});
