/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.DocumentBalanceViewModel();
});

describe('DocumentBalanceViewModel', function() {
  it('should create an instance of DocumentBalanceViewModel', function() {
    // uncomment below and update the code to test DocumentBalanceViewModel
    //var instance = new SiigoApi.DocumentBalanceViewModel();
    //expect(instance).to.be.a(SiigoApi.DocumentBalanceViewModel);
  });

  it('should have the property type (base name: "type")', function() {
    // uncomment below and update the code to test the property type
    //var instance = new SiigoApi.DocumentBalanceViewModel();
    //expect(instance).to.be();
  });

  it('should have the property totalPurchased (base name: "total_purchased")', function() {
    // uncomment below and update the code to test the property totalPurchased
    //var instance = new SiigoApi.DocumentBalanceViewModel();
    //expect(instance).to.be();
  });

  it('should have the property used (base name: "used")', function() {
    // uncomment below and update the code to test the property used
    //var instance = new SiigoApi.DocumentBalanceViewModel();
    //expect(instance).to.be();
  });

  it('should have the property available (base name: "available")', function() {
    // uncomment below and update the code to test the property available
    //var instance = new SiigoApi.DocumentBalanceViewModel();
    //expect(instance).to.be();
  });

});
