/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.Due();
});

describe('Due', function() {
  it('should create an instance of Due', function() {
    // uncomment below and update the code to test Due
    //var instance = new SiigoApi.Due();
    //expect(instance).to.be.a(SiigoApi.Due);
  });

  it('should have the property prefix (base name: "prefix")', function() {
    // uncomment below and update the code to test the property prefix
    //var instance = new SiigoApi.Due();
    //expect(instance).to.be();
  });

  it('should have the property consecutive (base name: "consecutive")', function() {
    // uncomment below and update the code to test the property consecutive
    //var instance = new SiigoApi.Due();
    //expect(instance).to.be();
  });

  it('should have the property quote (base name: "quote")', function() {
    // uncomment below and update the code to test the property quote
    //var instance = new SiigoApi.Due();
    //expect(instance).to.be();
  });

  it('should have the property date (base name: "date")', function() {
    // uncomment below and update the code to test the property date
    //var instance = new SiigoApi.Due();
    //expect(instance).to.be();
  });

});
