/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.EInvoiceErrorViewModel();
});

describe('EInvoiceErrorViewModel', function() {
  it('should create an instance of EInvoiceErrorViewModel', function() {
    // uncomment below and update the code to test EInvoiceErrorViewModel
    //var instance = new SiigoApi.EInvoiceErrorViewModel();
    //expect(instance).to.be.a(SiigoApi.EInvoiceErrorViewModel);
  });

  it('should have the property code (base name: "code")', function() {
    // uncomment below and update the code to test the property code
    //var instance = new SiigoApi.EInvoiceErrorViewModel();
    //expect(instance).to.be();
  });

  it('should have the property message (base name: "message")', function() {
    // uncomment below and update the code to test the property message
    //var instance = new SiigoApi.EInvoiceErrorViewModel();
    //expect(instance).to.be();
  });

});
