/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.ErrorResponse();
});

describe('ErrorResponse', function() {
  it('should create an instance of ErrorResponse', function() {
    // uncomment below and update the code to test ErrorResponse
    //var instance = new SiigoApi.ErrorResponse();
    //expect(instance).to.be.a(SiigoApi.ErrorResponse);
  });

  it('should have the property status (base name: "status")', function() {
    // uncomment below and update the code to test the property status
    //var instance = new SiigoApi.ErrorResponse();
    //expect(instance).to.be();
  });

  it('should have the property errors (base name: "errors")', function() {
    // uncomment below and update the code to test the property errors
    //var instance = new SiigoApi.ErrorResponse();
    //expect(instance).to.be();
  });

});
