/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.ErrorDetail();
});

describe('ErrorDetail', function() {
  it('should create an instance of ErrorDetail', function() {
    // uncomment below and update the code to test ErrorDetail
    //var instance = new SiigoApi.ErrorDetail();
    //expect(instance).to.be.a(SiigoApi.ErrorDetail);
  });

  it('should have the property code (base name: "code")', function() {
    // uncomment below and update the code to test the property code
    //var instance = new SiigoApi.ErrorDetail();
    //expect(instance).to.be();
  });

  it('should have the property message (base name: "message")', function() {
    // uncomment below and update the code to test the property message
    //var instance = new SiigoApi.ErrorDetail();
    //expect(instance).to.be();
  });

  it('should have the property params (base name: "params")', function() {
    // uncomment below and update the code to test the property params
    //var instance = new SiigoApi.ErrorDetail();
    //expect(instance).to.be();
  });

  it('should have the property detail (base name: "detail")', function() {
    // uncomment below and update the code to test the property detail
    //var instance = new SiigoApi.ErrorDetail();
    //expect(instance).to.be();
  });

});
