/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.FiscalResponsibilitiesCommand();
});

describe('FiscalResponsibilitiesCommand', function() {
  it('should create an instance of FiscalResponsibilitiesCommand', function() {
    // uncomment below and update the code to test FiscalResponsibilitiesCommand
    //var instance = new SiigoApi.FiscalResponsibilitiesCommand();
    //expect(instance).to.be.a(SiigoApi.FiscalResponsibilitiesCommand);
  });

  it('should have the property code (base name: "code")', function() {
    // uncomment below and update the code to test the property code
    //var instance = new SiigoApi.FiscalResponsibilitiesCommand();
    //expect(instance).to.be();
  });

  it('should have the property name (base name: "name")', function() {
    // uncomment below and update the code to test the property name
    //var instance = new SiigoApi.FiscalResponsibilitiesCommand();
    //expect(instance).to.be();
  });

});
