/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.InvoiceDeleteViewModel();
});

describe('InvoiceDeleteViewModel', function() {
  it('should create an instance of InvoiceDeleteViewModel', function() {
    // uncomment below and update the code to test InvoiceDeleteViewModel
    //var instance = new SiigoApi.InvoiceDeleteViewModel();
    //expect(instance).to.be.a(SiigoApi.InvoiceDeleteViewModel);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SiigoApi.InvoiceDeleteViewModel();
    //expect(instance).to.be();
  });

  it('should have the property deleted (base name: "deleted")', function() {
    // uncomment below and update the code to test the property deleted
    //var instance = new SiigoApi.InvoiceDeleteViewModel();
    //expect(instance).to.be();
  });

});
