/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.InvoiceStampViewModel();
});

describe('InvoiceStampViewModel', function() {
  it('should create an instance of InvoiceStampViewModel', function() {
    // uncomment below and update the code to test InvoiceStampViewModel
    //var instance = new SiigoApi.InvoiceStampViewModel();
    //expect(instance).to.be.a(SiigoApi.InvoiceStampViewModel);
  });

  it('should have the property uuid (base name: "uuid")', function() {
    // uncomment below and update the code to test the property uuid
    //var instance = new SiigoApi.InvoiceStampViewModel();
    //expect(instance).to.be();
  });

  it('should have the property status (base name: "status")', function() {
    // uncomment below and update the code to test the property status
    //var instance = new SiigoApi.InvoiceStampViewModel();
    //expect(instance).to.be();
  });

  it('should have the property observations (base name: "observations")', function() {
    // uncomment below and update the code to test the property observations
    //var instance = new SiigoApi.InvoiceStampViewModel();
    //expect(instance).to.be();
  });

  it('should have the property errors (base name: "errors")', function() {
    // uncomment below and update the code to test the property errors
    //var instance = new SiigoApi.InvoiceStampViewModel();
    //expect(instance).to.be();
  });

});
