/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.InvoicePdfViewModel();
});

describe('InvoicePdfViewModel', function() {
  it('should create an instance of InvoicePdfViewModel', function() {
    // uncomment below and update the code to test InvoicePdfViewModel
    //var instance = new SiigoApi.InvoicePdfViewModel();
    //expect(instance).to.be.a(SiigoApi.InvoicePdfViewModel);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SiigoApi.InvoicePdfViewModel();
    //expect(instance).to.be();
  });

  it('should have the property cufe (base name: "cufe")', function() {
    // uncomment below and update the code to test the property cufe
    //var instance = new SiigoApi.InvoicePdfViewModel();
    //expect(instance).to.be();
  });

  it('should have the property base64 (base name: "base64")', function() {
    // uncomment below and update the code to test the property base64
    //var instance = new SiigoApi.InvoicePdfViewModel();
    //expect(instance).to.be();
  });

});
