/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.ItemTransportData();
});

describe('ItemTransportData', function() {
  it('should create an instance of ItemTransportData', function() {
    // uncomment below and update the code to test ItemTransportData
    //var instance = new SiigoApi.ItemTransportData();
    //expect(instance).to.be.a(SiigoApi.ItemTransportData);
  });

  it('should have the property fileNumber (base name: "file_number")', function() {
    // uncomment below and update the code to test the property fileNumber
    //var instance = new SiigoApi.ItemTransportData();
    //expect(instance).to.be();
  });

  it('should have the property shipmentNumber (base name: "shipment_number")', function() {
    // uncomment below and update the code to test the property shipmentNumber
    //var instance = new SiigoApi.ItemTransportData();
    //expect(instance).to.be();
  });

  it('should have the property transportedQuantity (base name: "transported_quantity")', function() {
    // uncomment below and update the code to test the property transportedQuantity
    //var instance = new SiigoApi.ItemTransportData();
    //expect(instance).to.be();
  });

  it('should have the property measurementUnit (base name: "measurement_unit")', function() {
    // uncomment below and update the code to test the property measurementUnit
    //var instance = new SiigoApi.ItemTransportData();
    //expect(instance).to.be();
  });

  it('should have the property freightValue (base name: "freight_value")', function() {
    // uncomment below and update the code to test the property freightValue
    //var instance = new SiigoApi.ItemTransportData();
    //expect(instance).to.be();
  });

  it('should have the property purchaseOrder (base name: "purchase_order")', function() {
    // uncomment below and update the code to test the property purchaseOrder
    //var instance = new SiigoApi.ItemTransportData();
    //expect(instance).to.be();
  });

  it('should have the property serviceType (base name: "service_type")', function() {
    // uncomment below and update the code to test the property serviceType
    //var instance = new SiigoApi.ItemTransportData();
    //expect(instance).to.be();
  });

});
