/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.ItemsModel();
});

describe('ItemsModel', function() {
  it('should create an instance of ItemsModel', function() {
    // uncomment below and update the code to test ItemsModel
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be.a(SiigoApi.ItemsModel);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be();
  });

  it('should have the property code (base name: "code")', function() {
    // uncomment below and update the code to test the property code
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be();
  });

  it('should have the property quantity (base name: "quantity")', function() {
    // uncomment below and update the code to test the property quantity
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be();
  });

  it('should have the property price (base name: "price")', function() {
    // uncomment below and update the code to test the property price
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be();
  });

  it('should have the property seller (base name: "seller")', function() {
    // uncomment below and update the code to test the property seller
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be();
  });

  it('should have the property description (base name: "description")', function() {
    // uncomment below and update the code to test the property description
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be();
  });

  it('should have the property discount (base name: "discount")', function() {
    // uncomment below and update the code to test the property discount
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be();
  });

  it('should have the property taxes (base name: "taxes")', function() {
    // uncomment below and update the code to test the property taxes
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be();
  });

  it('should have the property warehouse (base name: "warehouse")', function() {
    // uncomment below and update the code to test the property warehouse
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be();
  });

  it('should have the property total (base name: "total")', function() {
    // uncomment below and update the code to test the property total
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be();
  });

  it('should have the property vatExcluded (base name: "vat_excluded")', function() {
    // uncomment below and update the code to test the property vatExcluded
    //var instance = new SiigoApi.ItemsModel();
    //expect(instance).to.be();
  });

});
