/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.JournalEntryProductCommand();
});

describe('JournalEntryProductCommand', function() {
  it('should create an instance of JournalEntryProductCommand', function() {
    // uncomment below and update the code to test JournalEntryProductCommand
    //var instance = new SiigoApi.JournalEntryProductCommand();
    //expect(instance).to.be.a(SiigoApi.JournalEntryProductCommand);
  });

  it('should have the property code (base name: "code")', function() {
    // uncomment below and update the code to test the property code
    //var instance = new SiigoApi.JournalEntryProductCommand();
    //expect(instance).to.be();
  });

  it('should have the property warehouse (base name: "warehouse")', function() {
    // uncomment below and update the code to test the property warehouse
    //var instance = new SiigoApi.JournalEntryProductCommand();
    //expect(instance).to.be();
  });

  it('should have the property quantity (base name: "quantity")', function() {
    // uncomment below and update the code to test the property quantity
    //var instance = new SiigoApi.JournalEntryProductCommand();
    //expect(instance).to.be();
  });

});
