/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.LinksPagination();
});

describe('LinksPagination', function() {
  it('should create an instance of LinksPagination', function() {
    // uncomment below and update the code to test LinksPagination
    //var instance = new SiigoApi.LinksPagination();
    //expect(instance).to.be.a(SiigoApi.LinksPagination);
  });

  it('should have the property previous (base name: "previous")', function() {
    // uncomment below and update the code to test the property previous
    //var instance = new SiigoApi.LinksPagination();
    //expect(instance).to.be();
  });

  it('should have the property self (base name: "self")', function() {
    // uncomment below and update the code to test the property self
    //var instance = new SiigoApi.LinksPagination();
    //expect(instance).to.be();
  });

  it('should have the property next (base name: "next")', function() {
    // uncomment below and update the code to test the property next
    //var instance = new SiigoApi.LinksPagination();
    //expect(instance).to.be();
  });

});
