/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.Link();
});

describe('Link', function() {
  it('should create an instance of Link', function() {
    // uncomment below and update the code to test Link
    //var instance = new SiigoApi.Link();
    //expect(instance).to.be.a(SiigoApi.Link);
  });

  it('should have the property href (base name: "href")', function() {
    // uncomment below and update the code to test the property href
    //var instance = new SiigoApi.Link();
    //expect(instance).to.be();
  });

});
