/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.LiteCustomerCommand();
});

describe('LiteCustomerCommand', function() {
  it('should create an instance of LiteCustomerCommand', function() {
    // uncomment below and update the code to test LiteCustomerCommand
    //var instance = new SiigoApi.LiteCustomerCommand();
    //expect(instance).to.be.a(SiigoApi.LiteCustomerCommand);
  });

  it('should have the property identification (base name: "identification")', function() {
    // uncomment below and update the code to test the property identification
    //var instance = new SiigoApi.LiteCustomerCommand();
    //expect(instance).to.be();
  });

  it('should have the property branchOffice (base name: "branch_office")', function() {
    // uncomment below and update the code to test the property branchOffice
    //var instance = new SiigoApi.LiteCustomerCommand();
    //expect(instance).to.be();
  });

});
