/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.MailCommand();
});

describe('MailCommand', function() {
  it('should create an instance of MailCommand', function() {
    // uncomment below and update the code to test MailCommand
    //var instance = new SiigoApi.MailCommand();
    //expect(instance).to.be.a(SiigoApi.MailCommand);
  });

  it('should have the property send (base name: "send")', function() {
    // uncomment below and update the code to test the property send
    //var instance = new SiigoApi.MailCommand();
    //expect(instance).to.be();
  });

});
