/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.MailViewModel();
});

describe('MailViewModel', function() {
  it('should create an instance of MailViewModel', function() {
    // uncomment below and update the code to test MailViewModel
    //var instance = new SiigoApi.MailViewModel();
    //expect(instance).to.be.a(SiigoApi.MailViewModel);
  });

  it('should have the property status (base name: "status")', function() {
    // uncomment below and update the code to test the property status
    //var instance = new SiigoApi.MailViewModel();
    //expect(instance).to.be();
  });

  it('should have the property observations (base name: "observations")', function() {
    // uncomment below and update the code to test the property observations
    //var instance = new SiigoApi.MailViewModel();
    //expect(instance).to.be();
  });

});
