/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.MetadataModel();
});

describe('MetadataModel', function() {
  it('should create an instance of MetadataModel', function() {
    // uncomment below and update the code to test MetadataModel
    //var instance = new SiigoApi.MetadataModel();
    //expect(instance).to.be.a(SiigoApi.MetadataModel);
  });

  it('should have the property created (base name: "created")', function() {
    // uncomment below and update the code to test the property created
    //var instance = new SiigoApi.MetadataModel();
    //expect(instance).to.be();
  });

  it('should have the property lastUpdated (base name: "last_updated")', function() {
    // uncomment below and update the code to test the property lastUpdated
    //var instance = new SiigoApi.MetadataModel();
    //expect(instance).to.be();
  });

});
