/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.PageListModel();
});

describe('PageListModel', function() {
  it('should create an instance of PageListModel', function() {
    // uncomment below and update the code to test PageListModel
    //var instance = new SiigoApi.PageListModel();
    //expect(instance).to.be.a(SiigoApi.PageListModel);
  });

  it('should have the property page (base name: "page")', function() {
    // uncomment below and update the code to test the property page
    //var instance = new SiigoApi.PageListModel();
    //expect(instance).to.be();
  });

  it('should have the property pageSize (base name: "page_size")', function() {
    // uncomment below and update the code to test the property pageSize
    //var instance = new SiigoApi.PageListModel();
    //expect(instance).to.be();
  });

  it('should have the property totalResults (base name: "total_results")', function() {
    // uncomment below and update the code to test the property totalResults
    //var instance = new SiigoApi.PageListModel();
    //expect(instance).to.be();
  });

});
