/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.PaymentsModel();
});

describe('PaymentsModel', function() {
  it('should create an instance of PaymentsModel', function() {
    // uncomment below and update the code to test PaymentsModel
    //var instance = new SiigoApi.PaymentsModel();
    //expect(instance).to.be.a(SiigoApi.PaymentsModel);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SiigoApi.PaymentsModel();
    //expect(instance).to.be();
  });

  it('should have the property name (base name: "name")', function() {
    // uncomment below and update the code to test the property name
    //var instance = new SiigoApi.PaymentsModel();
    //expect(instance).to.be();
  });

  it('should have the property value (base name: "value")', function() {
    // uncomment below and update the code to test the property value
    //var instance = new SiigoApi.PaymentsModel();
    //expect(instance).to.be();
  });

  it('should have the property dueDate (base name: "due_date")', function() {
    // uncomment below and update the code to test the property dueDate
    //var instance = new SiigoApi.PaymentsModel();
    //expect(instance).to.be();
  });

});
