/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.PaymentTypeViewModel();
});

describe('PaymentTypeViewModel', function() {
  it('should create an instance of PaymentTypeViewModel', function() {
    // uncomment below and update the code to test PaymentTypeViewModel
    //var instance = new SiigoApi.PaymentTypeViewModel();
    //expect(instance).to.be.a(SiigoApi.PaymentTypeViewModel);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SiigoApi.PaymentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property name (base name: "name")', function() {
    // uncomment below and update the code to test the property name
    //var instance = new SiigoApi.PaymentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property type (base name: "type")', function() {
    // uncomment below and update the code to test the property type
    //var instance = new SiigoApi.PaymentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property active (base name: "active")', function() {
    // uncomment below and update the code to test the property active
    //var instance = new SiigoApi.PaymentTypeViewModel();
    //expect(instance).to.be();
  });

  it('should have the property dueDate (base name: "due_date")', function() {
    // uncomment below and update the code to test the property dueDate
    //var instance = new SiigoApi.PaymentTypeViewModel();
    //expect(instance).to.be();
  });

});
