/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.PhoneModel();
});

describe('PhoneModel', function() {
  it('should create an instance of PhoneModel', function() {
    // uncomment below and update the code to test PhoneModel
    //var instance = new SiigoApi.PhoneModel();
    //expect(instance).to.be.a(SiigoApi.PhoneModel);
  });

  it('should have the property indicative (base name: "indicative")', function() {
    // uncomment below and update the code to test the property indicative
    //var instance = new SiigoApi.PhoneModel();
    //expect(instance).to.be();
  });

  it('should have the property number (base name: "number")', function() {
    // uncomment below and update the code to test the property number
    //var instance = new SiigoApi.PhoneModel();
    //expect(instance).to.be();
  });

  it('should have the property extension (base name: "extension")', function() {
    // uncomment below and update the code to test the property extension
    //var instance = new SiigoApi.PhoneModel();
    //expect(instance).to.be();
  });

});
