/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.PricesListProducts();
});

describe('PricesListProducts', function() {
  it('should create an instance of PricesListProducts', function() {
    // uncomment below and update the code to test PricesListProducts
    //var instance = new SiigoApi.PricesListProducts();
    //expect(instance).to.be.a(SiigoApi.PricesListProducts);
  });

  it('should have the property position (base name: "position")', function() {
    // uncomment below and update the code to test the property position
    //var instance = new SiigoApi.PricesListProducts();
    //expect(instance).to.be();
  });

  it('should have the property value (base name: "value")', function() {
    // uncomment below and update the code to test the property value
    //var instance = new SiigoApi.PricesListProducts();
    //expect(instance).to.be();
  });

});
