/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.PricesProducts();
});

describe('PricesProducts', function() {
  it('should create an instance of PricesProducts', function() {
    // uncomment below and update the code to test PricesProducts
    //var instance = new SiigoApi.PricesProducts();
    //expect(instance).to.be.a(SiigoApi.PricesProducts);
  });

  it('should have the property currencyCode (base name: "currency_code")', function() {
    // uncomment below and update the code to test the property currencyCode
    //var instance = new SiigoApi.PricesProducts();
    //expect(instance).to.be();
  });

  it('should have the property priceList (base name: "price_list")', function() {
    // uncomment below and update the code to test the property priceList
    //var instance = new SiigoApi.PricesProducts();
    //expect(instance).to.be();
  });

});
