/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.RelatedUsersModel();
});

describe('RelatedUsersModel', function() {
  it('should create an instance of RelatedUsersModel', function() {
    // uncomment below and update the code to test RelatedUsersModel
    //var instance = new SiigoApi.RelatedUsersModel();
    //expect(instance).to.be.a(SiigoApi.RelatedUsersModel);
  });

  it('should have the property sellerId (base name: "seller_id")', function() {
    // uncomment below and update the code to test the property sellerId
    //var instance = new SiigoApi.RelatedUsersModel();
    //expect(instance).to.be();
  });

  it('should have the property collectorId (base name: "collector_id")', function() {
    // uncomment below and update the code to test the property collectorId
    //var instance = new SiigoApi.RelatedUsersModel();
    //expect(instance).to.be();
  });

});
