/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.SendElectronicVoucherCommand();
});

describe('SendElectronicVoucherCommand', function() {
  it('should create an instance of SendElectronicVoucherCommand', function() {
    // uncomment below and update the code to test SendElectronicVoucherCommand
    //var instance = new SiigoApi.SendElectronicVoucherCommand();
    //expect(instance).to.be.a(SiigoApi.SendElectronicVoucherCommand);
  });

  it('should have the property guid (base name: "guid")', function() {
    // uncomment below and update the code to test the property guid
    //var instance = new SiigoApi.SendElectronicVoucherCommand();
    //expect(instance).to.be();
  });

  it('should have the property mailTo (base name: "mail_to")', function() {
    // uncomment below and update the code to test the property mailTo
    //var instance = new SiigoApi.SendElectronicVoucherCommand();
    //expect(instance).to.be();
  });

  it('should have the property copyTo (base name: "copy_to")', function() {
    // uncomment below and update the code to test the property copyTo
    //var instance = new SiigoApi.SendElectronicVoucherCommand();
    //expect(instance).to.be();
  });

});
