/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.SendElectronicInvoiceViewModel();
});

describe('SendElectronicInvoiceViewModel', function() {
  it('should create an instance of SendElectronicInvoiceViewModel', function() {
    // uncomment below and update the code to test SendElectronicInvoiceViewModel
    //var instance = new SiigoApi.SendElectronicInvoiceViewModel();
    //expect(instance).to.be.a(SiigoApi.SendElectronicInvoiceViewModel);
  });

  it('should have the property stamp (base name: "stamp")', function() {
    // uncomment below and update the code to test the property stamp
    //var instance = new SiigoApi.SendElectronicInvoiceViewModel();
    //expect(instance).to.be();
  });

  it('should have the property mail (base name: "mail")', function() {
    // uncomment below and update the code to test the property mail
    //var instance = new SiigoApi.SendElectronicInvoiceViewModel();
    //expect(instance).to.be();
  });

});
