/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.StampViewModel();
});

describe('StampViewModel', function() {
  it('should create an instance of StampViewModel', function() {
    // uncomment below and update the code to test StampViewModel
    //var instance = new SiigoApi.StampViewModel();
    //expect(instance).to.be.a(SiigoApi.StampViewModel);
  });

  it('should have the property status (base name: "status")', function() {
    // uncomment below and update the code to test the property status
    //var instance = new SiigoApi.StampViewModel();
    //expect(instance).to.be();
  });

  it('should have the property cufe (base name: "cufe")', function() {
    // uncomment below and update the code to test the property cufe
    //var instance = new SiigoApi.StampViewModel();
    //expect(instance).to.be();
  });

  it('should have the property cude (base name: "cude")', function() {
    // uncomment below and update the code to test the property cude
    //var instance = new SiigoApi.StampViewModel();
    //expect(instance).to.be();
  });

  it('should have the property observations (base name: "observations")', function() {
    // uncomment below and update the code to test the property observations
    //var instance = new SiigoApi.StampViewModel();
    //expect(instance).to.be();
  });

  it('should have the property errors (base name: "errors")', function() {
    // uncomment below and update the code to test the property errors
    //var instance = new SiigoApi.StampViewModel();
    //expect(instance).to.be();
  });

});
