/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.TestBalanceResultModel();
});

describe('TestBalanceResultModel', function() {
  it('should create an instance of TestBalanceResultModel', function() {
    // uncomment below and update the code to test TestBalanceResultModel
    //var instance = new SiigoApi.TestBalanceResultModel();
    //expect(instance).to.be.a(SiigoApi.TestBalanceResultModel);
  });

  it('should have the property fileId (base name: "file_id")', function() {
    // uncomment below and update the code to test the property fileId
    //var instance = new SiigoApi.TestBalanceResultModel();
    //expect(instance).to.be();
  });

  it('should have the property fileUrl (base name: "file_url")', function() {
    // uncomment below and update the code to test the property fileUrl
    //var instance = new SiigoApi.TestBalanceResultModel();
    //expect(instance).to.be();
  });

});
