/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.UsersModel();
});

describe('UsersModel', function() {
  it('should create an instance of UsersModel', function() {
    // uncomment below and update the code to test UsersModel
    //var instance = new SiigoApi.UsersModel();
    //expect(instance).to.be.a(SiigoApi.UsersModel);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SiigoApi.UsersModel();
    //expect(instance).to.be();
  });

  it('should have the property username (base name: "username")', function() {
    // uncomment below and update the code to test the property username
    //var instance = new SiigoApi.UsersModel();
    //expect(instance).to.be();
  });

  it('should have the property firstName (base name: "first_name")', function() {
    // uncomment below and update the code to test the property firstName
    //var instance = new SiigoApi.UsersModel();
    //expect(instance).to.be();
  });

  it('should have the property lastName (base name: "last_name")', function() {
    // uncomment below and update the code to test the property lastName
    //var instance = new SiigoApi.UsersModel();
    //expect(instance).to.be();
  });

  it('should have the property email (base name: "email")', function() {
    // uncomment below and update the code to test the property email
    //var instance = new SiigoApi.UsersModel();
    //expect(instance).to.be();
  });

  it('should have the property active (base name: "active")', function() {
    // uncomment below and update the code to test the property active
    //var instance = new SiigoApi.UsersModel();
    //expect(instance).to.be();
  });

  it('should have the property identification (base name: "identification")', function() {
    // uncomment below and update the code to test the property identification
    //var instance = new SiigoApi.UsersModel();
    //expect(instance).to.be();
  });

});
