/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import * as SiigoApi from "../../src/index.js";
import expect from "expect.js";

let instance;

beforeEach(function() {
  instance = new SiigoApi.Warehouse();
});

describe('Warehouse', function() {
  it('should create an instance of Warehouse', function() {
    // uncomment below and update the code to test Warehouse
    //var instance = new SiigoApi.Warehouse();
    //expect(instance).to.be.a(SiigoApi.Warehouse);
  });

  it('should have the property id (base name: "id")', function() {
    // uncomment below and update the code to test the property id
    //var instance = new SiigoApi.Warehouse();
    //expect(instance).to.be();
  });

  it('should have the property name (base name: "name")', function() {
    // uncomment below and update the code to test the property name
    //var instance = new SiigoApi.Warehouse();
    //expect(instance).to.be();
  });

  it('should have the property quantity (base name: "quantity")', function() {
    // uncomment below and update the code to test the property quantity
    //var instance = new SiigoApi.Warehouse();
    //expect(instance).to.be();
  });

});
