/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import app from "../app.js";
import expect from "expect.js";

let instance;

before(async function() {
  let SiigoAPI = await app.initialize();
  instance = new SiigoAPI.CustomerApi();
});

describe('CustomerApi', function() {
  describe('createCustomer', function() {
    it('should call createCustomer successfully', async function() {
      try {
        let result = await instance.createCustomerWithHttpInfo({});
        expect(result.response.statusCode).to.be.greaterThan(199);
        expect(result.response.statusCode).to.be.lessThan(300);
      } catch (error) {
        expect(error.status).to.be.greaterThan(399);
        expect(error.status).to.be.lessThan(500);
      }      
    });
  });
  describe('deleteCustomer', function() {
    it('should call deleteCustomer successfully', async function() {
      try {
        let result = await instance.deleteCustomerWithHttpInfo({});
        expect(result.response.statusCode).to.be.greaterThan(199);
        expect(result.response.statusCode).to.be.lessThan(300);
      } catch (error) {
        expect(error.status).to.be.greaterThan(399);
        expect(error.status).to.be.lessThan(500);
      }      
    });
  });
  describe('getCustomer', function() {
    it('should call getCustomer successfully', async function() {
      try {
        let result = await instance.getCustomerWithHttpInfo({});
        expect(result.response.statusCode).to.be.greaterThan(199);
        expect(result.response.statusCode).to.be.lessThan(300);
      } catch (error) {
        expect(error.status).to.be.greaterThan(399);
        expect(error.status).to.be.lessThan(500);
      }      
    });
  });
  describe('getCustomers', function() {
    it('should call getCustomers successfully', async function() {
      try {
        let result = await instance.getCustomersWithHttpInfo({});
        expect(result.response.statusCode).to.be.greaterThan(199);
        expect(result.response.statusCode).to.be.lessThan(300);
      } catch (error) {
        expect(error.status).to.be.greaterThan(399);
        expect(error.status).to.be.lessThan(500);
      }      
    });
  });
  describe('updateCustomer', function() {
    it('should call updateCustomer successfully', async function() {
      try {
        let result = await instance.updateCustomerWithHttpInfo({});
        expect(result.response.statusCode).to.be.greaterThan(199);
        expect(result.response.statusCode).to.be.lessThan(300);
      } catch (error) {
        expect(error.status).to.be.greaterThan(399);
        expect(error.status).to.be.lessThan(500);
      }      
    });
  });
});

