name: test

on:
  pull_request:
    branches: [dev]

jobs: 
  test:
    name: Integration Test 
    runs-on: ubuntu-latest
    env:
      BASE_PATH: ${{secrets.BASE_PATH}} 
      URL_SIGN_IN: ${{secrets.URL_SIGN_IN}} 
      USER_NAME: ${{secrets.USER_NAME}} 
      ACCESS_KEY: ${{secrets.ACCESS_KEY}}     
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npx ci
    - name: Test
      run: npm test
